export const UNIVERSE_GRADIENTS = {
  zeus: "linear-gradient(135deg, #7C6CFF 0%, #4A56C6 100%)",
  poseidon: "linear-gradient(135deg, #4FCBFF 0%, #3F7FD2 100%)",
  athena: "linear-gradient(135deg, #D6DBFF 0%, #8D94CC 100%)",
  aphrodite: "linear-gradient(135deg, #F4B6C8 0%, #B989B7 100%)",
  apollon: "linear-gradient(135deg, #F7C39A 0%, #C98663 100%)",
  hermes: "linear-gradient(135deg, #55E6D5 0%, #4A9FB0 100%)",
  ares: "linear-gradient(135deg, #9FA9C9 0%, #586487 100%)",
  demeter: "linear-gradient(135deg, #7AE3C2 0%, #63AB95 100%)",
  artemis: "linear-gradient(135deg, #6C5AE8 0%, #41339E 100%)",
  hephaistos: "linear-gradient(135deg, #F29B5C 0%, #C4664A 100%)",
  dionysos: "linear-gradient(135deg, #D85AE5 0%, #8B439C 100%)",
  hestia: "linear-gradient(135deg, #E9C0BA 0%, #C9939E 100%)",
};

export const UNIVERSES = [
  {
    id: "zeus",
    label: "Zeus",
    subtitle: "Point Zéro",
    title: "Orchestration globale",
    visualHook: "Le flux souverain qui relie tous les rôles du mariage sans jamais casser la lecture d'ensemble.",
    columns: [
      { title: "Pour les mariés", text: "Gardez la vision d’ensemble sans porter le bruit opérationnel du mariage." },
      { title: "Pour le planner", text: "Centralisez validations, rôles, timings et décisions sensibles dans la même vue." },
      { title: "Ce que cela tient", text: "Budget, documents, diffusion et jour J restent alignés sans perte d’information." },
    ],
    image: "/landing/zeus.jpg",
    route: "/univers/zeus",
    moduleRoute: "/point-zero",
    menuItems: [
      { label: "Cockpit", to: "/point-zero" },
      { label: "Alertes", to: "/notifications" },
      { label: "Jour J", to: "/jour-j" },
    ],
  },
  {
    id: "poseidon",
    label: "Poséidon",
    subtitle: "Ambiance sonore",
    title: "Son, lumière & ambiance",
    visualHook: "L'immersion émotionnelle d'un mariage ne se pilote pas à l'instinct : elle se prépare comme une vague parfaitement tenue.",
    columns: [
      { title: "Pour les mariés", text: "L’ambiance se prépare par séquences, pas par intuition de dernière minute." },
      { title: "Pour les partenaires", text: "DJ, son, lumière et timing lisent tous le même déroulé partagé." },
      { title: "Ce que cela règle", text: "Cocktail, dîner, entrée, ouverture de bal et soirée gardent le bon rythme." },
    ],
    image: "/landing/poseidon.jpg",
    route: "/univers/poseidon",
    moduleRoute: "/prestataires?category=music",
    menuItems: [
      { label: "Son", to: "/prestataires?category=music" },
      { label: "Soirée", to: "/univers/dionysos" },
      { label: "Prestataires", to: "/prestataires" },
    ],
  },
  {
    id: "athena",
    label: "Athéna",
    subtitle: "Planning",
    title: "Stratégie & automatisation",
    visualHook: "La vraie intelligence d'un mariage se joue dans l'anticipation, pas dans l'accumulation de formulaires.",
    columns: [
      { title: "Pour les mariés", text: "Vous voyez ce qui mérite une décision, pas tout le bruit de préparation." },
      { title: "Pour le planner", text: "Rappels, alertes et dépendances se lisent avant de devenir des urgences." },
      { title: "Ce que cela anticipe", text: "Météo, accès, retards, invités et arbitrages sensibles sont remontés plus tôt." },
    ],
    image: "/landing/athena.jpg",
    route: "/univers/athena",
    moduleRoute: "/point-zero?section=reminders",
    menuItems: [
      { label: "Rappels", to: "/point-zero?section=reminders" },
      { label: "Alertes", to: "/notifications" },
      { label: "Automations", to: "/point-zero?section=automations" },
    ],
  },
  {
    id: "aphrodite",
    label: "Aphrodite",
    subtitle: "Esthétique",
    title: "Scénographie & esthétique",
    visualHook: "La beauté du mariage devient plus forte quand elle est cadrée, transmise et relue comme un langage partagé.",
    columns: [
      { title: "Pour les mariés", text: "L’esthétique reste tenue sans se perdre entre captures, messages et validations." },
      { title: "Pour les partenaires", text: "Fleurs, déco, scénographie et implantation partagent la même direction visuelle." },
      { title: "Ce que cela cadre", text: "Ambiance, matières, palette et circulation visuelle du lieu restent cohérentes." },
    ],
    image: "/landing/aphrodite.jpg",
    route: "/univers/aphrodite",
    moduleRoute: "/documents",
    menuItems: [
      { label: "Moodboard", to: "/univers/aphrodite" },
      { label: "Documents", to: "/documents" },
      { label: "Fleurs & déco", to: "/prestataires?category=flowers-decor" },
    ],
  },
  {
    id: "apollon",
    label: "Apollon",
    subtitle: "Souvenirs",
    title: "Photo, vidéo & souvenirs",
    visualHook: "La mémoire du mariage dépend d'une lumière tenue, d'un rythme juste et de séquences réellement respectées.",
    columns: [
      { title: "Pour les mariés", text: "Les souvenirs gagnent en justesse quand les bons moments sont protégés." },
      { title: "Pour les partenaires", text: "Photo et vidéo savent quand intervenir, où se placer et quoi couvrir." },
      { title: "Ce que cela préserve", text: "Fenêtres de lumière, transitions, captation et galerie finale restent bien tenues." },
    ],
    image: "/landing/apollon.jpg",
    route: "/univers/apollon",
    moduleRoute: "/espace-invites",
    menuItems: [
      { label: "Galerie", to: "/univers/apollon" },
      { label: "Invités", to: "/espace-invites" },
      { label: "Photo / vidéo", to: "/prestataires?category=photo-video" },
    ],
  },
  {
    id: "hermes",
    label: "Hermès",
    subtitle: "Communication",
    title: "Communication & diffusion",
    visualHook: "Un mariage se fragilise quand l'information circule mal. Hermès raconte la vitesse, mais surtout la justesse du message.",
    columns: [
      { title: "Pour les mariés", text: "Vous recevez les bonnes informations au bon moment, sans surcharge inutile." },
      { title: "Pour les partenaires", text: "Les échanges restent clairs, tracés et reliés aux pièces réellement utiles." },
      { title: "Ce que cela diffuse", text: "Messages, relances, plans B et documents partagés partent au bon public." },
    ],
    image: "/landing/hermes.jpg",
    route: "/univers/hermes",
    moduleRoute: "/communication",
    menuItems: [
      { label: "Messages", to: "/communication" },
      { label: "Documents", to: "/documents" },
      { label: "Prestataires", to: "/prestataires" },
    ],
  },
  {
    id: "ares",
    label: "Arès",
    subtitle: "Jour J",
    title: "Régie terrain & exécution",
    visualHook: "Le terrain n'a rien de poétique quand il déraille. Il doit être précis, rapide et maintenu sans panique.",
    columns: [
      { title: "Pour les mariés", text: "Le terrain reste invisible quand il fonctionne vraiment bien." },
      { title: "Pour les partenaires", text: "Montage, circulation, mobilier et incidents se pilotent sans flottement." },
      { title: "Ce que cela exécute", text: "Implantation, accès, chronologie et check final restent lisibles sous pression." },
    ],
    image: "/landing/ares.jpg",
    route: "/univers/ares",
    moduleRoute: "/jour-j",
    menuItems: [
      { label: "Timeline", to: "/jour-j" },
      { label: "Prestataires", to: "/prestataires" },
      { label: "Plan B", to: "/documents" },
    ],
  },
  {
    id: "demeter",
    label: "Déméter",
    subtitle: "Budget",
    title: "Table, service & ressources",
    visualHook: "Le dîner, les régimes, le service et les arbitrages budgétaires forment un même système, pas des sujets séparés.",
    columns: [
      { title: "Pour les mariés", text: "Le dîner se décide avec goût, mais aussi avec cohérence réelle." },
      { title: "Pour les partenaires", text: "Traiteur, régimes, tables et volumes parlent le même langage." },
      { title: "Ce que cela tient", text: "Menus, allergies, service, budget repas et rythme du dîner restent alignés." },
    ],
    image: "/landing/demeter.jpg",
    route: "/univers/demeter",
    moduleRoute: "/budget",
    menuItems: [
      { label: "Budget", to: "/budget" },
      { label: "Invités", to: "/invites" },
      { label: "Traiteur", to: "/prestataires?category=catering" },
    ],
  },
  {
    id: "artemis",
    label: "Artémis",
    subtitle: "Registre",
    title: "Lieux & espaces",
    visualHook: "Le lieu n'est pas un décor fixe. C'est une matière vivante : accès, météo, flux, accueil, extérieur, repli.",
    columns: [
      { title: "Pour les mariés", text: "Le lieu se choisit pour son usage réel, pas seulement pour sa photo." },
      { title: "Pour les partenaires", text: "Capacité, accès, repli météo et logistique se lisent dès la recherche." },
      { title: "Ce que cela éclaire", text: "Distance, disponibilité, style, circulation et plan B sont visibles plus tôt." },
    ],
    image: "/landing/artemis.jpg",
    route: "/univers/artemis",
    moduleRoute: "/prestataires?category=venue",
    menuItems: [
      { label: "Lieux", to: "/prestataires?category=venue" },
      { label: "Registre", to: "/prestataires" },
      { label: "Setup", to: "/setup" },
    ],
  },
  {
    id: "hephaistos",
    label: "Héphaïstos",
    subtitle: "Supports",
    title: "Outils & supports sur-mesure",
    visualHook: "Quand le mariage demande une fiche, un export, une feuille ou un support spécifique, il faut pouvoir le forger proprement.",
    columns: [
      { title: "Pour les mariés", text: "Les supports restent beaux, lisibles et prêts au bon moment." },
      { title: "Pour les partenaires", text: "Papeterie, exports et feuilles de rôle se fabriquent sans friction." },
      { title: "Ce que cela produit", text: "Faire-part, menus, plans, PDF et rendus finaux sortent au bon format." },
    ],
    image: "/landing/hephaistos.jpg",
    route: "/univers/hephaistos",
    moduleRoute: "/exports",
    menuItems: [
      { label: "Exports", to: "/exports" },
      { label: "Documents", to: "/documents" },
      { label: "Supports", to: "/univers/hephaistos" },
    ],
  },
  {
    id: "dionysos",
    label: "Dionysos",
    subtitle: "Soirée",
    title: "Fête & soirée",
    visualHook: "La nuit réussie d'un mariage est le résultat d'un enchaînement tenu, pas d'un simple bouton fête.",
    columns: [
      { title: "Pour les mariés", text: "La soirée garde son intensité sans casser le déroulé de la journée." },
      { title: "Pour les partenaires", text: "Animations, bar, ouverture et after se calent sur le vrai tempo." },
      { title: "Ce que cela amplifie", text: "Énergie, programmation, temps forts et fin de soirée restent cohérents." },
    ],
    image: "/landing/dionysos.jpg",
    route: "/univers/dionysos",
    moduleRoute: "/prestataires?category=music",
    menuItems: [
      { label: "Soirée", to: "/univers/dionysos" },
      { label: "Jour J", to: "/jour-j" },
      { label: "Animations", to: "/prestataires?category=music" },
    ],
  },
  {
    id: "hestia",
    label: "Hestia",
    subtitle: "Invités",
    title: "Accueil, famille & transmission",
    visualHook: "Un mariage reste un foyer temporaire : il faut accueillir, rassurer, relier et transmettre l'expérience à toutes les générations.",
    columns: [
      { title: "Pour les mariés", text: "L’accueil reste doux, lisible et humain pour toutes les générations." },
      { title: "Pour les proches", text: "Famille, témoins, enfants et aînés trouvent leur place sans flottement." },
      { title: "Ce que cela protège", text: "RSVP, tables, foyers, hébergements et lien humain du mariage restent tenus." },
    ],
    image: "/landing/hestia.jpg",
    route: "/univers/hestia",
    moduleRoute: "/invites",
    menuItems: [
      { label: "Invités", to: "/invites" },
      { label: "RSVP", to: "/espace-invites" },
      { label: "Couple", to: "/couple" },
    ],
  },
];

export function getUniverseById(id) {
  return UNIVERSES.find((item) => item.id === id) || null;
}
